---
editor_options:
  markdown:
    wrap: 72
---

```{r}
library(tidyverse)
library(drc)
library(dplyr)
library(plyr)
library(ggpmisc)
library(RColorBrewer)
library(openxlsx)
library(forcats)
library(lme4)
library(Matrix)
library(stringr)
library(reshape2)
library(pwr)
library(effsize)
library(ggsignif)
library(readr)

#load(".RData")
```

Load in data

```{r}
this_dir <- getwd()

# get file
file <- list.files(this_dir, pattern = "clean.csv", full.names = TRUE)

# read csv
session_log <- read.csv(file)

df <- data.frame(session_log)
```

turn dataset into hourly
```{r}
# Count how many trips departed from each station during each hour
df_hourly <- df %>%
  dplyr::group_by(
    start_station_id,
    hour,
    day_of_week,
    day_of_month,
    weekend,
    workingday,
    is_rush_hour
  ) %>%
  dplyr::summarise(
    demand = dplyr::n(),
    .groups = 'drop'
  )

filename <- "hourly.csv"
write_csv(df_hourly, filename)
```

shrink dataset
```{r}
# Reduce to 2 weeks of data
df_sample <- df_hourly %>%
  filter(day_of_month <= 14)

nrow(df_sample)  # Should be ~50-60k rows

write.csv(df_sample, "hourly_2weeks.csv", row.names = FALSE, na = "?")
```

clean environment
```{r}
#rm(list = ls())
```



